{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocket-id.fullname" . }}-config
data:
  {{- if .Values.ingress.enabled -}}
  {{- if not .Values.config.publicAppUrl  }}
  {{- required "publicAppUrl needs to be set if using an ingress" .Values.config.publicAppUrl }}
  {{- else if and .Values.ingress.tls (not (hasPrefix "https" .Values.config.publicAppUrl)) }}
  {{- fail "value for .Values.config.publicAppUrl needs to start with 'https://' when using tls" }}
  {{- end }}
  TRUST_PROXY: "true"
  {{- end }}
  {{- range $key := keys .Values.config }}
  {{ $key | snakecase | upper }}: {{ get $.Values.config $key }}
  {{- end }}
{{- end }}
